web:
  build: .
  environment:
    DATABASE_URL: ecto://chat:chat@db/chat_prod
    PORT: 4001
  links:
    - db
  ports:
    - 4001:4001
db:
  image: postgres
  environment:
    POSTGRES_USER: chat
    POSTGRES_PASSWORD: chat
